Localization Update
OpenLitterMap/openlittermap-web pull request #231
Opened 2021-06-01 19:05 UTC by jpablogomezb

- Spanish language 100% done.
- More dynamic translation tags were added mainly within langs/ for 'Profile' (langs/"lg"/profile_dashboard) and 'Teams' (langs/"lg"/teams_dashboard), and somer Vue components. Therefore, it is now possible to finish the translation in other languages using the new json files.

2021-06-01 20:07 UTC, xlcrr requested changes
Great work. Some good code here, but some changes are needed before we can merge. Try to keep PRs small as it helps review, debug and merge

2021-06-01 20:07 UTC, xlcrr commented on resources/js/components/Profile/top/ProfileWelcome.vue
> +        <p>{{ $t('profile_dashboard.top.in-position') }} {{ usersPosition }} {{ $t('profile_dashboard.top.place') }}</p>
When we want to input a variable into a translation string, we do 
```
let myRank = '1st';

$t('profile.dashboard.rank', { rank: myRank ]);

// "profile.dashboard.rank": "You are in {rank} place";
```

2021-06-01 20:07 UTC, xlcrr commented on resources/js/langs/de/index.js
> +import { profile_dashboard } from './profile_dashboard/index';
Ideally, profile should be a parent of dashboard `profile.dashboard`

2021-06-01 20:07 UTC, xlcrr commented on resources/js/langs/de/index.js
> +import { teams_dashboard } from './teams_dashboard/index';
Teams should also be a parent of dashboard. `teams.dashboard`

2021-06-01 20:07 UTC, xlcrr commented on resources/js/langs/de/index.js
> +import del_image_comp from './del_image_comp.json';
what is _comp? We should use clearer key names eg `profile`, `teams`, `locations`

2021-06-01 20:07 UTC, xlcrr commented on resources/js/langs/de/profile_dashboard/middle.json
> +    "radar-cat-brands": "brands",
We have already translated the categories? We do not need translation values for the key names

2021-06-01 20:18 UTC, xlcrr commented on resources/js/langs/de/index.js
> +import { profile_dashboard } from './profile_dashboard/index';
Look at how other data structures have a parent-child relationship

2021-06-03 22:27 UTC, jpablogomezb commented on resources/js/components/Charts/Radar.vue
> +                    label: this.$t('profile_dashboard.middle.radar-total-categories'), //'Total Categories',
Mmm...since it is only a title label of the graphic, I left it using the localisation: label: this.$t('profile.dashboard.total-categories')

2021-06-06 21:17 UTC, xlcrr commented
Need any help? @jpablogomezb

2021-06-07 09:49 UTC, xlcrr requested changes
Nice work. We are missing some translations for DE, NL and PL. Can you ask @FredMark and @Xamyrz to help translate them? Then we can merge this huge PR! Great work!

2021-06-07 09:49 UTC, xlcrr commented on resources/js/langs/de/index.js
> -import teams from './teams.json';
Keep the list a-z please

2021-06-07 09:49 UTC, xlcrr commented on resources/js/langs/es/teams_old_backup.json
> +        "all": "Todo",
Missing

2021-06-07 09:49 UTC, xlcrr commented on resources/js/langs/nl/common.json
> +    "inactive": "Inactive"
Many missing translations here. Can you ask @FredMark  to translate them before we merge?

2021-06-11 20:30 UTC, xlcrr approved these changes

2021-06-11 20:36 UTC, merged